services:
  credential-issuer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # environment:
    #   NODE_ENV: production
    #   BLOCKCHAIN_RPC_PROVIDER: ${BLOCKCHAIN_RPC_PROVIDER}
    #   BLOCKCHAIN_CHAIN_ID: ${BLOCKCHAIN_CHAIN_ID}
    #   BLOCKCHAIN_DID_REGISTRY_ADDR: ${BLOCKCHAIN_DID_REGISTRY_ADDR}
    #   BLOCKCHAIN_MERKLE_ADDR: ${BLOCKCHAIN_MERKLE_ADDR}
    #   FASTIFY_CONFIG: ${FASTIFY_CONFIG}
    #   # VERAMO_SECRET_KEY will be generated inside the container
    env_file:
      - .env
    volumes:
      # Mount specific directories/files instead of the entire project
      - ./src:/app/src
      - ./config:/app/config
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./tsconfig.json:/app/tsconfig.json
      # Use an anonymous volume for node_modules
      - /app/node_modules
    restart: unless-stopped
